[pytest]
log_cli = true
log_cli_level = INFO
testpaths = tests
python_files = test_*.py
addopts =
    -ra
    --alluredir=allure-results
markers =
    smoke:smoke tests
    regression:regression tests
    api: api related tests
    performance: api performance tests