name: Regression night tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write
  pages: write

jobs:
  run_ui_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: python -m playwright install --with-deps

      - name: Create .env for variables
        run: echo "${{ vars.ENV_FILE }}" > .env

      - name: Run regression tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: pytest -m "regression and not api" --alluredir=allure-results

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-artifacts-ui-${{ matrix.browser }}
          path: |
            artifacts
            allure-results
          retention-days: 7

  run_api_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create .env for variables
        run: echo "${{ vars.ENV_FILE }}" > .env

      - name: Run regression tests
        run: pytest -m "regression and api" --alluredir=allure-results

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-artifacts-api
          path: |
            artifacts
            allure-results
          retention-days: 7

  merge_and_deploy_results:
    if: always()
    needs: [run_ui_tests, run_api_tests]
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: test-artifacts

      - name: Merge into one dir
        run: |
          mkdir allure-results
          find test-artifacts -type d -name "allure-results" -print0 | while IFS= read -r -d '' d; do
            cp -R "$d/." allure-results/
          done

      - name: Add environment details to allure results
        id: add-environment-details
        if: always()
        run: |
          echo "Run=${{  github.run_number  }}" >> allure-results/environment.properties
          echo "Branch=${{  github.ref_name  }}" >> allure-results/environment.properties
          echo "BuildTime=$(date +'%H:%M:%S %m-%d-%Y')" >> allure-results/environment.properties
          cat allure-results/environment.properties

      - name: Get Allure History from gh-pages
        uses: actions/checkout@v7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report from history and results
        uses: simple-elf/allure-report-action@v1.14
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Upload generated Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

      - name: Deploy report to Github Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{  secrets.GITHUB_TOKEN  }}
          publish_branch: gh-pages
          publish_dir: allure-history
          commit_message: Deploy report to Github Pages